spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      location: ${java.io.tmpdir}
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/mall
  messages:
    basename: messagges # default value
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
apiPrefix: api
